// require('./packages-built/meteor.js')
// require('./global.js')

require('./server_environment.js')
require('./helpers.js')
Meteor._debug = console.log.bind(console)
Meteor._setImmediate = process.nextTick
Meteor.setTimeout = setTimeout.bind(global)
Meteor.setInterval = setInterval.bind(global)
Meteor.clearInterval = clearInterval.bind(global)
require('./timers.js')
require('./errors.js')
require('./fiber_helpers.js')
require('./startup_server.js')
require('./string_utils.js')
require('./dynamics_nodejs.js')
require('./url_server.js')
require('./url_common.js')
require('./flush-buffers-on-exit-in-windows.js')